server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://192.168.0.53:5432/musify
    username: postgres
    password: Dudzio1423
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

jwt:
  auth:
    app: authapp
    secret_key: wLDxR+IUyNhGP11Tlay8Wk1WwVea5tdFOAaCHH6ZWy8=
    expires_in: 3600

eureka:
  client:
    enabled: false
