# Serwer
server.port=8080

# Spring Application
spring.application.name=api_gateway
spring.main.web-application-type=reactive

# DataSource
spring.datasource.url=jdbc:postgresql://192.168.0.53:5432/musify
spring.datasource.username=postgres
spring.datasource.password=Dudzio1423

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Wy??czenie Security AutoConfiguration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration

# Spring Cloud Gateway Routes
spring.cloud.gateway.routes[0].id=user_service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[1].id=product_service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/products/**
spring.cloud.gateway.routes[1].predicates[1]=Path=/api/categories/tree

spring.cloud.gateway.routes[2].id=order_service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/orders/**

spring.cloud.gateway.routes[3].id=review_service
spring.cloud.gateway.routes[3].uri=http://localhost:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/reviews/**

# Global CORS
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedOrigins=http://localhost:3000,http://frontend.mydomain.com
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedHeaders=Authorization,Content-Type
spring.cloud.gateway.globalcors.cors-configurations[/**].exposedHeaders=Authorization
spring.cloud.gateway.globalcors.cors-configurations[/**].allowCredentials=true

# Security
spring.security.basic.enabled=false

# JWT
jwt.auth.app=authapp
jwt.auth.secret_key=wLDxR+IUyNhGP11Tlay8Wk1WwVea5tdFOAaCHH6ZWy8=
jwt.auth.expires_in=3600

# Logging Levels
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG

spring.cloud.gateway.default-filters[0]=RemoveRequestHeader=Authorization