server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  datasource:
    url: jdbc:postgresql://192.168.0.53:5432/musify
    username: postgres
    password: Dudzio1423
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
#          filters:
#           - AddRequestHeader=X-Forwarded-Authorization, #{auth_token}
        - id: product-service
          uri: http://product-service:8082
          predicates:
            - Path=/api/products/**
            - Path=/api/categories/**
#          filters:
#            - AddRequestHeader=X-Forwarded-Authorization, #{auth_token}
        - id: order-service
          uri: http://order-service:8083
          predicates:
            - Path=/api/orders/**
#          filters:
#            - AddRequestHeader=X-Forwarded-Authorization, #{auth_token}
        - id: review-service
          uri: http://review-service:8084
          predicates:
            - Path=/api/reviews/**
#          filters:
#            - AddRequestHeader=X-Forwarded-Authorization, #{auth_token}
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD

jwt:
  auth:
    app: authapp
    secret_key: wLDxR+IUyNhGP11Tlay8Wk1WwVea5tdFOAaCHH6ZWy8=
    expires_in: 3600

logging:
  level:
    org.springframework.security: DEBUG